version: '3.7'

services:
  php:
    build: ./docker/php
    volumes:
      - ./backend:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /var/www/html
    environment:
      XDEBUG_MODE: develop,coverage,debug,profile
      PHP_IDE_CONFIG: "serverName=docker"

  nginx:
    image: nginx:latest
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - "3306:3306"